### ISSUE TITLE
add default documentation to this repo

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/sanctuarywatch#1]
To encourage participation and/or simply document how this repository functions, I recommend adding a few standard documentation pieces to this repository.

For more information on each of the below items, see https://opensource.guide/starting-a-project/#launching-your-own-open-source-project

- [x] license
- [x] update readme with a little more context (answering some questions such as; What does this project do? Why is this project useful? How do I get started? Where can I get more help, if I need it?)
- [x] contributing guidelines
- [x] code of conduct

**Comment by superjai** [comment]
Good idea! I should have done this already, to be honest.
