### ISSUE TITLE
add font awesome icons to figure link labels

### ISSUE THREAD

**Issue by superjai** [ioos/sanctuarywatch#11]
currently the figure link labels look as follows:
<img width="470" alt="Screenshot 2024-08-14 at 2 26 50 PM" src="https://github.com/user-attachments/assets/d7c1492d-9570-4c18-8d01-07bd0ae7549b">
However, we want two relevant font awesome icons to show up as below:
<img width="871" alt="Screenshot 2024-08-14 at 2 28 34 PM" src="https://github.com/user-attachments/assets/a908c91a-82b9-48d8-a904-4339626d77de">

The first step is to enqueue the font awesome stylesheet from a cdn, [like this one](https://cdnjs.com/libraries/font-awesome).

To actually use a particular icon, you use the `<i>` tag, as follows:
`<i class="fa-solid fa-database"></i>
`
You can search the font awesome library [here](https://fontawesome.com/icons/database?f=classic&s=solid).

**Comment by skanda-vasishta** [comment]
<i class="fa-solid fa-database"></i> 
`let icon1 = `<i class="fa fa-clipboard-list" role="presentation" aria-label="clipboard-list icon" style=""></i> `;
`    let icon2 = `<i class="fa fa-database" role="presentation" aria-label="database icon"></i>`;
`
` added similar icons to two links:
`    firstLink.appendChild(document.createTextNode(info_obj['scienceText']));
`
...
`    secondLink.innerHTML = icon2 + `  ` + secondLink.innerHTML;
`

**Comment by skanda-vasishta** [comment]
added fa icons;
https://github.com/ioos/sanctuarywatch/blob/ebf79dd83deb873765f7d05c125001023a90c99f/themes/Sanctuary_Watch/assets/js/script.js#L843 
from 843 to 860
