### ISSUE TITLE
layout for modal header messed up in landscape mobile view

### ISSUE THREAD

**Issue by superjai** [ioos/sanctuarywatch#12]
In landscape mobile view, the modal top row looks as follows:

<img width="577" alt="Screenshot 2024-08-14 at 2 40 24 PM" src="https://github.com/user-attachments/assets/f4b2c0fc-0a0c-4456-9ece-9d3bf9233d61">

**Comment by skanda-vasishta** [comment]
fixed within  mobile_helper and make_title functions, as well as within style.css media queries
