### ISSUE TITLE
improving accessibility of modal windows

### ISSUE THREAD

**Issue by superjai** [ioos/sanctuarywatch#14]
Currently, using keyboard controls only, you can't really navigate in a modal window. Here is [some advice](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/dialog/) on how to handle that using `<aria>` tags and other things. Apparently, the keyboard control you want to use exit out of a modal window is Esc.

Additionally, I created a html page in chatGPT to create the functionality we want (github doesn't allow attaching raw html files, so I had to zip it). You can localhost this page  and then take a look. Hopefully some stuff in here will be useful in the Wordpress theme.
[test1.html.zip](https://github.com/user-attachments/files/16640920/test1.html.zip)

**Comment by skanda-vasishta** [comment]
trapfocus function: https://github.com/ioos/sanctuarywatch/blob/ebf79dd83deb873765f7d05c125001023a90c99f/themes/Sanctuary_Watch/assets/js/script.js#L12
needs some work, still some weird behavior
