### ISSUE TITLE
add aria-labelledby to modal

### ISSUE THREAD

**Issue by superjai** [ioos/sanctuarywatch#15]
To improve our accessibility, let's add an aria tag to the modal window. Within the following `<div>` tag that describes the modal, let's add an [aria-labelledby](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby) pointing at the id "modal-title".
`<div class="modal-content">`
becomes
`<div class="modal-content" aria-labelledby="modal-title">`

**Comment by skanda-vasishta** [comment]
added aria label within single-scene.php to modal-content
