### ISSUE TITLE
change button color

### ISSUE THREAD

**Issue by superjai** [ioos/sanctuarywatch#16]
Can you please change the following button color to #00467F
That will get more of a match with the colors on the page
<img width="1343" alt="Screenshot 2024-08-19 at 1 37 15 PM" src="https://github.com/user-attachments/assets/c9b50bdd-a5c4-48ae-bb92-fcd909fe194d">

**Comment by skanda-vasishta** [comment]
fixed; link.className = 'btn ';
...
link.setAttribute("style", "display: flex; justify-content: center; align-items: center; color: white !important; background-color: #00467F !important");
