### ISSUE TITLE
add anchor tag to individual tabs

### ISSUE THREAD

**Issue by superjai** [ioos/sanctuarywatch#17]
Right now, if you are linking to Sanctuary Watch from another site, the best you can do is to link to an individual scene. But what if you want to link to a particular tab within a particular modal? Well, you can't do that now, but let's add that feature.

Here is an example. I created the following tab:
<img width="1095" alt="Screenshot 2024-08-19 at 1 40 18 PM" src="https://github.com/user-attachments/assets/348c62a3-93b7-4295-9d0b-6b83c50d980b">

It would be great to be able to connect directly to this tab as either:
1. root-url/instance-slug/kelp-forest#CA_Sheephead_Trend_Pisco
2. root-url/instance-slug/kelp-forest#Trend_Pisco
3. some better way

The first option, within the anchor tag, combines the icon and tab title. That makes the anchor tag longer and more ungainly, but reduces the chances for duplicate anchor tag values. Note that special characters are removed from the tab in the anchor tag.

The second option provides just the tab title as the anchor tag. Play around with this to see which option (or some other option as the anchor tag) seems best.

The idea would be, I think, to add an event listener for the onload event for the scene. Upon onload, check the url to see if a `.hash` is present (the anchor link). If the anchor link is present, go directly to that tab.

Of course, the other half of the equation is that the user has to know what the full url for a tab should be (in case they would want to use that url as a hyperlink). I am not exactly sure how this should be presented in the user. Maybe in either  of the locations in the image above (marked as the red 1 or 2)? And I am picturing that the user would click on the link and that would be copied to the clipboard. Similar to how, here in [Font Awesome](https://fontawesome.com/icons/gauge?f=classic&s=solid), if you click on `<i class="fa-solid fa-gauge"></i>`, that code snippet is directly copied to the clipboard. 

Thoughts? This is still a little fuzzy.

**Comment by superjai** [comment]
If the anchor tag approach to linking to the modal seems like a dead end, another approach might be via the [GET HTTP method](https://www.w3schools.com/tags/ref_httpmethods.asp). You could put, in the arguments of the method, something that would indicate that a specific modal tab should be opened. It would create an odd looking hyperlink though.

**Comment by skanda-vasishta** [comment]
currently works, format of URLs would be option 2. Option 1 (or something slightly modified) might be easier though cuz we wouldn't have to explicitly find the modal window on which the figure is found. Also, in case there are redundant tab names, it might be best to include the parent modal:
root-url/instance-slug/kelp-forest#CA_Sheephead/Trend_Pisco

**Comment by skanda-vasishta** [comment]
resolved: created async function built on event handlers to open specific tab based on hyperlink:
https://github.com/ioos/sanctuarywatch/blob/ef543d346145f544a38a2d8daf95decb06cddce1/themes/Sanctuary_Watch/assets/js/script.js#L1732

also, modified create_tabs function to facilitate url parsing, and to actually create the URL:
https://github.com/ioos/sanctuarywatch/blob/ef543d346145f544a38a2d8daf95decb06cddce1/themes/Sanctuary_Watch/assets/js/script.js#L1020

**Comment by skanda-vasishta** [comment]
Add button to copy tab link to clipboard somewhere

**Comment by skanda-vasishta** [comment]
> Add button to copy tab link to clipboard somewhere

works as long as browser protocol is https

**Comment by skanda-vasishta** [comment]
modified fix to make it work on dev side of things: 
added new function called waitForElement, which uses mutation observer to wait for elements to render before firing event handlers instead of timeout (which can get messy, not always intended behavior)
