### ISSUE TITLE
more noticeable focus color

### ISSUE THREAD

**Issue by superjai** [ioos/sanctuarywatch#18]
The on focus color is currently yellow, which is a little hard to see against a white background (see below). Maybe pick a color which is a little easier to see?
<img width="1178" alt="Screenshot 2024-08-19 at 1 11 24 PM" src="https://github.com/user-attachments/assets/799acbdd-f027-4e79-8cd1-a81431fa3924">

**Comment by skanda-vasishta** [comment]
changed to red
