### ISSUE TITLE
Menu link not working

### ISSUE THREAD

**Issue by superjai** [ioos/sanctuarywatch#20]
The first menu link for the scene isn't working. Let me demonstrate with an example. In the example below, the overview scene is designated as Kelp Forest, which is the scene that is currently shown. If I click on "Channel Islands NMS" (red arrow)...

<img width="1854" alt="Screenshot 2024-08-19 at 4 13 11 PM" src="https://github.com/user-attachments/assets/f8198ee3-76dd-4abe-a71e-09bee766459e">

I am taken to the overall screen for Sanctuary Watch. Note the web address (red arrow below)
<img width="1528" alt="Screenshot 2024-08-19 at 4 13 28 PM" src="https://github.com/user-attachments/assets/1539c8d0-99b8-4ac8-b64e-629df5b9a1fc">

**Comment by skanda-vasishta** [comment]
resolved: now takes user to overview scene; next step to fix overview link

**Comment by skanda-vasishta** [comment]
![image](https://github.com/user-attachments/assets/abd89e7e-d13f-4d24-b903-00fdeb3de6d1)
for some reason, this is blank on the dev site, but it works as intended on local

**Comment by skanda-vasishta** [comment]
> ![image](https://private-user-images.githubusercontent.com/124769936/361961688-abd89e7e-d13f-4d24-b903-00fdeb3de6d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NzYyNzAsIm5iZiI6MTcyNDg3NTk3MCwicGF0aCI6Ii8xMjQ3Njk5MzYvMzYxOTYxNjg4LWFiZDg5ZTdlLWQxM2YtNGQyNC1iOTAzLTAwZmRlYjNkZTZkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOFQyMDEyNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTRlYjMxODVjNGFjODIxMmQ4MjcwMzUyOGM1YmFmNWJhYjNkZGZkNThjODkwYjhlOGI0NzIwOWZhYWQ0MDdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BAFzjT0WsCgDkZMn858lmx-Emcyip3bKAhDm3SFLjOc) for some reason, this is blank on the dev site, but it works as intended on local

fixed: `echo "<a class='navbar-brand' href='/?post_type=scene&p=" . $inst_overview_scene . "'>$title</a>";`; next step is to make sure overview link is /name_of_instance, not /name_of_instance/name_of_overview_scene

**Comment by skanda-vasishta** [comment]
<img width="932" alt="image" src="https://github.com/user-attachments/assets/527a325e-1e26-4898-9ca9-149392ca6148">
scrapping this code for now but might be of use later

**Comment by skanda-vasishta** [comment]
<img width="932" alt="image" src="https://github.com/user-attachments/assets/2d219c78-3bf3-4195-bd54-9564b8e0e33e">
going to revert this code because I don't think I need it, but it's here for reference (the commented out stuff)

**Comment by skanda-vasishta** [comment]
https://github.com/ioos/sanctuarywatch/issues/20#issuecomment-2299647411 resolved
