### ISSUE TITLE
no links in gray figure bar if content doesn't exist

### ISSUE THREAD

**Issue by superjai** [ioos/sanctuarywatch#22]
Right now, within the gray bar above a figure, you see the two Font Awesome icons - even if there is no content in the associated "Monitoring program link" or "Data link" (see below).
<img width="1025" alt="Screenshot 2024-08-22 at 4 22 38 PM" src="https://github.com/user-attachments/assets/9604e3e6-3bfc-4841-82e6-7c733de82f70">

If there is no content for "Monitoring program link" and also "Data link", then the gray bar **should not** appear. If there is no content for one or the other, then the gray bar **should** appear but omit the Font Awesome icon for the field of no content.

**Comment by skanda-vasishta** [comment]
resolved, just some basic checks within render_tab_info to ensure fields are non-empty
