### ISSUE TITLE
Can't open tabs beyond the first one in a modal window

### ISSUE THREAD

**Issue by superjai** [ioos/sanctuarywatch#24]
In a modal window, you can't click to a tab beyond the first one. See below
<img width="1673" alt="Screenshot 2024-08-22 at 4 47 20 PM" src="https://github.com/user-attachments/assets/cf7da6d1-c483-4e43-93c3-dbf7adeaa7fb">

The issue is due to the '#' included in the query selector, which doesn't exist in the id. Check out the relevant id below, which doesn't have the '#'
<img width="1653" alt="Screenshot 2024-08-22 at 4 47 49 PM" src="https://github.com/user-attachments/assets/10a324a4-9fc3-4693-b2f7-69cb44d480b0">

**Comment by skanda-vasishta** [comment]
resolved: 
```
tab_id = tab_label.replace(/\s+/g, '_').replace(/[^a-zA-Z0-9_]/g, '_');
    title = title.replace(/\s+/g, '_').replace(/[^a-zA-Z0-9_]/g, '_');
```
