### ISSUE TITLE
increase modal width

### ISSUE THREAD

**Issue by superjai** [ioos/sanctuarywatch#27]
In desktop/tablet view, please increase the modal width to 70%.

**Comment by skanda-vasishta** [comment]
temporary fix; size is scaled upwards; will go back and change

**Comment by skanda-vasishta** [comment]
resolved; 
`figureDiv.setAttribute("style", "width: 100% !important; height: auto; display: block; margin: 0; margin-top: 2%");
    img.setAttribute("style", "width: 100% !important; height: auto; display: block; margin: 0; margin-top: 2%");`
