### ISSUE TITLE
photo/info accordions appearing even with no underlying links for scene & modal

### ISSUE THREAD

**Issue by superjai** [ioos/sanctuarywatch#30]
For both scene and modal, the accordions for photo and info appear even where are no underlying links.

Let's use an example. In the following scene Rocky Shore, you can see that there are no photo or info links.
<img width="1732" alt="Screenshot 2024-09-06 at 2 47 09 PM" src="https://github.com/user-attachments/assets/82c78ba5-8bbe-458b-94a8-599f5fa400c1">

But here is what we see in the resulting scene:
<img width="695" alt="Screenshot 2024-09-06 at 2 47 25 PM" src="https://github.com/user-attachments/assets/5293bf1d-e579-4914-9093-b99797ac032f">

There is the same behavior in modal. The theme should not add an accordion unless there is content in the related link fields.

**Comment by skanda-vasishta** [comment]
resolved, modified make_title function, validated by ensuring `scene_data['scene_info_entries'`]  and `scene_data['scene_photo_entries']` are non-zero, and only then calling `make_scene_elements`.
