### ISSUE TITLE
layout change for scene

### ISSUE THREAD

**Issue by superjai** [ioos/sanctuarywatch#31]
One suggestion from the team in terms of layout for the the Scene was to switch the position of the tagline and the info/photo accordions. So, in the row, let's try left-aligning the tagline (so that it appears under the title) and moving the accordions all the way to the right of the row.

We would want the modal to match, but let's not do that yet - let's first see if people like this layout better.

**Comment by skanda-vasishta** [comment]
resolved with some styling fixes
