### ISSUE TITLE
display wordpress-hosted images in scene

### ISSUE THREAD

**Issue by superjai** [ioos/sanctuarywatch#39]
Within the Scene, under the Images accordion, we want to be to display images that are hosted elsewhere (we have already implemented this) and images that are hosted within the wordpress site itself (not yet implemented). I have updated the plugin to allow for this, so if you could please do likewise on the theme, that would be great.

Within each "Scene Image Link" on the admin side of Wordpress, you will notice that there is now a dropdown (field name: scene_photo_location1 through scene_photo_location6). The value stored in the database is either "Internal" or "External". With a value of External, the theme should show images as it currently does. If the value is Internal, that means that there is an associated image that is stored within the wordpress media library. This image should be opened in a new tab. The path of this image is located within the fields scene_photo_internal1 through scene_photo_internal6.

This needs to be implemented within the modal window as well and I will get to work on that.

**Comment by skanda-vasishta** [comment]
Resolved: within `make_scene_elements`:
`              let scene_info_url;
                if (iUrl == "scene_photo_url"){
                    let photoLoc = "scene_photo_location" + i;
                    if (scene_data[info_field][photoLoc] == "External"){
                        scene_info_url = scene_data[info_field][info_url];
                    } else {
                        let internal = "scene_photo_internal" + i;
                        scene_info_url = scene_data[info_field][internal];
                    }
                }

                let scene_info_text = scene_data[info_field][info_text];`
