### ISSUE TITLE
Move API calls to PHP

### ISSUE THREAD

**Issue by superjai** [ioos/sanctuarywatch#49]
In the Scene, there are several places where an API call is used, where PHP could be used instead to get content from the database. Let's replace those API calls, where possible.

**Comment by skanda-vasishta** [comment]
Where can't I do this:

figures
modals

**Comment by skanda-vasishta** [comment]
potential refactors:
- `make_title` -- Can use inbuilt php api (ie `get_the_id` or whatever) to access information instead of API fetch
- `load_instance_details` -- same idea as before

**Comment by skanda-vasishta** [comment]
going to modify make_title, async call to api isn't ideal so I'm going to switch to using the wp inbuilt function

**Comment by skanda-vasishta** [comment]
> going to modify make_title, async call to api isn't ideal so I'm going to switch to using the wp inbuilt function

do this by registering a new endpoint with postmeta?

**Comment by skanda-vasishta** [comment]
done for the time being for scenes
