### ISSUE TITLE
scene behavior with single scene for sections

### ISSUE THREAD

**Issue by superjai** [ioos/sanctuarywatch#52]
In the scene custom content type, there is a new field `scene_same_hover_color_sections`. This field only comes to bear with an accordion or sectioned list table of contents type. When the value of this field is set to 'yes', the hover color for everything should be set to the value of `scene_hover_color`. Additionally (with a value of "yes", the hover color should not show as a background color in the table of contents.

I don't think you'll need an API call to make this work, so I didn't make it available that way. Let me know if you need anything.

Additionally, I have yet to implement the javascript for when the field is visible/not visible in the scene - but that shouldn't matter for your theme purposes.

**Comment by skanda-vasishta** [comment]
fixed: added validation for scene_same_hover_color_sections, which I accessed in single-scene.php
