### ISSUE TITLE
CSS theme fixes

### ISSUE THREAD

**Issue by superjai** [ioos/sanctuarywatch#54]
- [x] Modal and scene accordions: lighten color and decrease padding
- [x] Modal and scene accordions: dropdown arrow is sitting on top of the text (but shouldn't be)
- [x] Modal title: make more visible through some combination of color and bolding
- [x] Modal tab: make tab outline darker

**Comment by skanda-vasishta** [comment]
![image](https://github.com/user-attachments/assets/38b5abd7-38f1-4b60-a2ed-1275af497b07)this is the modified modal, let me know if I should change anything
