### ISSUE TITLE
Legacy content pointers

### ISSUE THREAD

**Issue by gkumaishi** [ioos/sanctuarywatch#56]
Need to point at GitHub pages until we are ready to point to WordPress for Florida Keys and SanctSound. Moving towards replacement with CINMS and OCNMS (but may be varied timelines).

**Comment by superjai** [comment]
I have added two new fields to the instance custom content type. When `instance_legacy_content` is set to "no", then the theme should work as-is. When this field is set to "yes", the tile should point to the contents of the field `instance_legacy_content_url`.

**Comment by skanda-vasishta** [comment]
resolved with some post meta calls for each instance in index.php: https://github.com/ioos/sanctuarywatch/commit/1bd92d31cb16099e4692203f69de00d28e1c24db#diff-d3463d3235faf891b028ad1392c0911e77517a070fdedafe5a49c0f4db3f920eR35
