### ISSUE TITLE
backend section issue

### ISSUE THREAD

**Issue by skanda-vasishta** [ioos/sanctuarywatch#57]
when section name is changed in backend, it should accordingly be reflected across other sections, but this doesn't happen:
ie. if i change section name from "section 1" to "section 2", the modals associated with section 1 should now be associated with section 2, and not "none"

**Comment by superjai** [comment]
@skanda-vasishta Fixed. You'll need to make an update in the theme though. In the modal content type, there is the field `icon_toc_section`, where the section is recorded. Up until now, the value recorded in this field was the section title. Now, the potential values in this field are "None" or "section_section1" through "section_section6". You will need to look up the associated section title for the table of contents.

**Comment by skanda-vasishta** [comment]
fixed: modified table of contents and nested helper functions, switched to using rest api call for this
