### ISSUE TITLE
Create footer for instance

### ISSUE THREAD

**Issue by superjai** [ioos/sanctuarywatch#58]
Please create a footer for each instance, based upon the following new fields in the instance custom content type: instance_contact_person and instance_more_info.

**Comment by skanda-vasishta** [comment]
![image](https://github.com/user-attachments/assets/7fe07a56-abf4-4695-9fac-e5e2c71d208d)

**Comment by skanda-vasishta** [comment]
resolved with https://github.com/ioos/sanctuarywatch/commit/1bd92d31cb16099e4692203f69de00d28e1c24db#diff-4a5dc502773d58bee89d215c1bb7335e36371a1d6643f9d723328a3e290b83d7R1142

**Comment by MathewBiddle** [comment]
Hey @superjai, just an FYI that there has been some effort towards standardizing the headers and footers for all the ioos.us websites. See this issue https://github.com/ioos/ioos-us/issues/263

While we haven't reached a decision yet, I recommend making your footer/header as potable as possible in the event that we request you to add the standardized ioos.us one.

cc: @mwengren in case he has additional comments.

potentially related to #12 too.
