### ISSUE TITLE
Add Sanctuary Watch Theme Details

### ISSUE THREAD

**Issue by superjai** [ioos/sanctuarywatch#6]
So, if we look at the current "Theme Details" for Sanctuary Watch in the WordPress Appearance screen, it looks a little bare:
![Screenshot 2024-07-03 at 12 05 49 PM](https://github.com/ioos/sanctuarywatch/assets/1744300/22548f0e-501d-4f3f-93c9-7bc16c3a67f5)

Compare this to the Theme Details for the WordPress theme Twenty Twenty Four:
![Screenshot 2024-07-03 at 12 07 22 PM](https://github.com/ioos/sanctuarywatch/assets/1744300/9472abfb-f5dd-4f36-be9f-c376a0ffafb0)

Let's go ahead and add an image as well as some additional text for the Theme Details for Sanctuary Watch:

- [x] Adding an image. Let's use a screenshot from the existing Sanctuary Watch site - maybe a modal window over a scene? To add this image, here are [instructions](https://wpism.com/wordpress-theme-screenshot/).

- [x] Adding text. To add text to the Theme Details, that all gets added to the header section of the style.css file. as [follows](https://developer.wordpress.org/themes/basics/main-stylesheet-style-css/).

**Comment by skanda-vasishta** [comment]
- added screenshot.png for image, modified style.css for other text details
