### ISSUE TITLE
alt text for external figure image

### ISSUE THREAD

**Issue by superjai** [ioos/sanctuarywatch#60]
There is a new field in the figure content type: `figure_external_alt`. When an external image is selected as the figure image, use the contents of `figure_external_alt` as the alt text for that image.

**Comment by skanda-vasishta** [comment]
resolved: see here: https://github.com/ioos/sanctuarywatch/commit/1bd92d31cb16099e4692203f69de00d28e1c24db#diff-4a5dc502773d58bee89d215c1bb7335e36371a1d6643f9d723328a3e290b83d7R1142
