### ISSUE TITLE
New draft scene feature

### ISSUE THREAD

**Issue by superjai** [ioos/sanctuarywatch#62]
I added a new field into the scene custom content type: `scene_published`. When `scene_published` is set to "published", then nothing should change on the theme. When the field is set to "draft", the scene should only be visible in the theme if the user is logged in - even if the instance is set to "published".

**Comment by skanda-vasishta** [comment]
done -- 
` $scene_published = get_post_meta(get_the_ID(), 'scene_published', true);`, then check that this !='draft' when populating elements
