### ISSUE TITLE
instance footer

### ISSUE THREAD

**Issue by superjai** [ioos/sanctuarywatch#63]
In the instance custom content type there is a new fieldset `instance_footer`, which contains the fields `instance_footer_about`, `instance_footer_contact`, and `instance_footer_reports`. Please use those fields to create the footer based upon the following image:
![footer](https://github.com/user-attachments/assets/2273297f-699c-4e5f-a88f-14c7bff1b971)
Please use a three column structure for the row, so that the footer still looks okay in mobile view.

Additionally, for the left column, the title should be "About the " with the third word being Sanctuary, Issue, or Designation, based upon the Instance type.

**Comment by skanda-vasishta** [comment]
closed
