### ISSUE TITLE
scene pages not displaying

### ISSUE THREAD

**Issue by superjai** [ioos/sanctuarywatch#71]
When attempting to go to a particular scene, I am directed towards the index page, even though the URL structure is correct. Here is an example for the Scene test11, which is part of Channel Islands NMS:
![Screenshot 2024-11-12 at 4 02 25 PM](https://github.com/user-attachments/assets/a8fcf8e5-3838-4f59-8459-d35a2892830f)

**Comment by skanda-vasishta** [comment]
resolved, fixes on the plugin side.
