### ISSUE TITLE
Footer issues

### ISSUE THREAD

**Issue by superjai** [ioos/sanctuarywatch#73]
1. The footer should not appear on the About page
2. In case of no content for a footer field - or in the worst case, all footer fields are blank - have the footer itself show up as blank, instead of the following:
![Screenshot 2024-11-14 at 4 37 02 PM](https://github.com/user-attachments/assets/9ddc324f-aa07-4d26-ba3e-7272a381eafd)

**Comment by MathewBiddle** [comment]
@mwengren do you have an approximate timeline for our ioos.us header/footer templates to be available for projects like this to incorporate?

@superjai please keep an eye on the progress in https://github.com/ioos/ioos-us/issues/263. For all ioos.us sites, we plan to release an insert-able header/footer to give a consistent look and feel to all of our sites. I'm not sure on the timeline, but I warn against spending too much time fixing header/footer issues as we will be providing updated guidance.

**Comment by mwengren** [comment]
I'm gong to redirect the question about timeline for implementing the templates to @sarinamann-noaa.

I'll add though that I think it's possible for an ioos.us sub-site to have dual footers if preferred.  In this case, the SanctuaryWatch footer could go above the site-wide ioos.us footer on the page.  This might affect the SanctuaryWatch site design in terms of style, but that can be up to them to adjust as needed.  All sites ioos.us sites will need to include the standard footer (and header), however.  

I expect the header to be more difficult to integrate with sites that have their own site-specific header, FWIW, including presumably this site.  This might require some styling changes to the ioos.us-wide header if it's determined it needs to be changed to be less prominent (smaller, lighter, ?).

cc @nguyandy

**Comment by skanda-vasishta** [comment]
errors fixed, see footer.php
